-
  hosts: all
  connection: local
  tasks:
    - name: launch ec2 instance for the instructor
      ec2:
        key_name: "{{aws_ec2.keypair_name}}"
        instance_type: "{{aws_ec2.instance_size}}"
        image: "{{aws_ec2.ami_id}}"
        wait: true
        group: "{{aws_ec2.security_group}}"
        assign_public_ip: "{{aws_ec2.assign_public_ip}}"
        region: "{{aws_ec2.region}}"
        vpc_subnet_id: "{{aws_ec2.subnet_id}}"
        count: 1
        instance_tags:
          Name: "Instructor"
          learn_deployment: true
          learn_deployment_student: false
          subdomain: "{{instructor.subdomain}}"
          zone: "{{cloudflare.domain}}"
      register: instructor_ec2

    - name: Create DNS record for instructor's server
      cloudflare_domain: >
        state=present
        name={{instructor.subdomain}}
        zone={{cloudflare.domain}}
        type=A
        content={{item.public_ip}}
        email={{cloudflare.email}}
        token={{cloudflare.token}}
      with_items:
        - "{{instructor_ec2.instances}}"